---
title: "R Notebook"
output: html_notebook
---

#Lê dados
require(readr);
contratos <- read_csv("dados/contratos.csv");

#Extrai coluna Valor inicial
valores <- data.matrix(contratos$'Valor inicial');

#Converte para fator
valores <- sub('R$', '', as.character(valores), fixed=TRUE);
valores <- gsub(',', '', as.character(valores), fixed=TRUE);
valores <- as.numeric(valores);
valores[is.na(valores)] <- 0
valores <- as.data.frame(valores)

#Extrai coluna Modalidade da Licitação
modalidades <- data.matrix(contratos$'Modalidade da Licitação')

#Converte para fator
for (row in 1:nrow(modalidades)) {
    modalidades[row] <- substring(modalidades[row], 1, 1);
}
modalidades <- make.names(modalidades, unique = FALSE, allow_ = TRUE)

modalidades <- as.factor(modalidades);

#random sample half the rows 
halfsample = sample(dim(valores)[1], dim(valores)[1]/4) # half of sample
#create training and test data sets
valores_treino = valores[halfsample,]
valores_teste = valores[-halfsample,]

valores_treino <- as.data.frame(valores_treino)
colnames(valores_treino) <- ("valores")


valores_teste <- as.data.frame(valores_teste)
colnames(valores_teste) <- ("valores")

modalidades_treino = modalidades[halfsample]
modalidades_teste = modalidades[-halfsample]


#AdaBoost
require(caret)

trainCtrlBag <- trainControl(method="repeatedcv", number = 2, repeats = 1, classProbs = TRUE, returnResamp = "all", verboseIter = TRUE)

tunegrid <- expand.grid(.mfinal = 30, .maxdepth = c(5:10))

model.adabag.1 <- train(valores_treino, modalidades_treino, method="AdaBag", tuneGrid=tunegrid, trControl=trainCtrlBag)

pred.test.adabag <- predict.train(model.adabag.1, valores_teste)
confusionMatrix(table(pred.test.adabag, modalidades_teste))